//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;arrayOfObj&quot;:[{&quot;foo&quot;: &quot;bar&quot;}]}.
        /// </summary>
        internal static string TestSnipperNestedChild {
            get {
                return ResourceManager.GetString("TestSnipperNestedChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///              &quot;array&quot;: [
        ///                1,
        ///                2,
        ///                3
        ///              ],
        ///              &quot;boolean&quot;: true,
        ///              &quot;color&quot;: &quot;#82b92c&quot;,
        ///              &quot;null&quot;: null,
        ///              &quot;number&quot;: 123,
        ///              &quot;object&quot;: {
        ///                &quot;a&quot;: &quot;b&quot;,
        ///                &quot;c&quot;: &quot;d&quot;,
        ///                &quot;e&quot;: &quot;f&quot;
        ///              },
        ///              &quot;string&quot;: &quot;Hello World&quot;,
        ///              &quot;arrayOfObj&quot;:[{&quot;foo&quot;: &quot;bar&quot;}]
        ///            }.
        /// </summary>
        internal static string TestSnippetFull {
            get {
                return ResourceManager.GetString("TestSnippetFull", resourceCulture);
            }
        }
    }
}
